import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { Textarea } from './ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import { Badge } from './ui/badge';
import { toast } from 'sonner';
import axios from 'axios';
import { 
  Brain, 
  FileText, 
  Stethoscope, 
  User, 
  Calendar,
  Sparkles,
  Copy,
  Download,
  RefreshCw,
  Clock,
  CheckCircle,
  Wand2
} from 'lucide-react';

const AIDocumentation = ({ user }) => {
  const [appointments, setAppointments] = useState([]);
  const [patients, setPatients] = useState([]);
  const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [selectedAppointment, setSelectedAppointment] = useState('');
  const [generatedNotes, setGeneratedNotes] = useState('');
  const [recentGenerations, setRecentGenerations] = useState([]);
  
  const [formData, setFormData] = useState({
    appointment_id: '',
    patient_symptoms: '',
    examination_findings: '',
    treatment_plan: ''
  });

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      const [appointmentsRes, patientsRes, usersRes] = await Promise.all([
        axios.get('/appointments'),
        axios.get('/patients'),
        user.role === 'admin' ? axios.get('/users') : Promise.resolve({ data: [] })
      ]);
      
      // Filter appointments that are completed or in progress
      const relevantAppointments = appointmentsRes.data.filter(apt => 
        apt.status === 'completed' || apt.status === 'scheduled'
      );
      
      setAppointments(relevantAppointments);
      setPatients(patientsRes.data);
      setUsers(usersRes.data);
      
      // Get recent appointments with AI notes
      const withAiNotes = relevantAppointments.filter(apt => apt.ai_generated_notes);
      setRecentGenerations(withAiNotes.slice(0, 5));
      
    } catch (error) {
      toast.error('Failed to fetch data');
      console.error('Error fetching data:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleGenerate = async (e) => {
    e.preventDefault();
    
    if (!formData.patient_symptoms || !formData.examination_findings || !formData.treatment_plan) {
      toast.error('Please fill in all required fields');
      return;
    }
    
    setGenerating(true);
    setGeneratedNotes('');
    
    try {
      const response = await axios.post('/ai/generate-notes', formData);
      setGeneratedNotes(response.data.generated_notes);
      toast.success('AI notes generated successfully!');
      
      // Refresh appointments to get updated data
      fetchData();
      
    } catch (error) {
      toast.error(error.response?.data?.detail || 'Failed to generate AI notes');
      console.error('Error generating notes:', error);
    } finally {
      setGenerating(false);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedNotes);
    toast.success('Notes copied to clipboard!');
  };

  const handleDownload = () => {
    const appointment = appointments.find(apt => apt.id === formData.appointment_id);
    const patient = getPatientInfo(appointment?.patient_id);
    
    const content = `
MEDICAL DOCUMENTATION

Patient: ${patient.user?.full_name || 'Unknown'}
Date: ${new Date().toLocaleDateString()}
Appointment: ${appointment?.reason || 'N/A'}

${generatedNotes}

Generated by AI Documentation Assistant
    `;
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `medical-notes-${patient.user?.full_name?.replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast.success('Notes downloaded successfully!');
  };

  const getPatientInfo = (patientId) => {
    const patient = patients.find(p => p.id === patientId);
    const patientUser = users.find(u => u.id === patient?.user_id);
    return { patient, user: patientUser };
  };

  const getDoctorInfo = (doctorId) => {
    return users.find(u => u.id === doctorId) || {};
  };

  const formatDate = (dateString) => {
    try {
      return new Date(dateString).toLocaleDateString();
    } catch {
      return dateString;
    }
  };

  if (loading) {
    return (
      <div className="space-y-6" data-testid="ai-docs-loading">
        <div className="animate-pulse">
          <div className="h-8 bg-gray-200 rounded w-1/3 mb-4"></div>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <div className="h-96 bg-gray-200 rounded-lg"></div>
            <div className="h-96 bg-gray-200 rounded-lg"></div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6 fade-in" data-testid="ai-documentation">
      {/* Header */}
      <div className="bg-gradient-to-r from-purple-600 to-pink-600 rounded-2xl p-8 text-white relative overflow-hidden">
        <div className="absolute top-0 right-0 transform translate-x-16 -translate-y-8">
          <div className="w-32 h-32 bg-white/10 rounded-full"></div>
        </div>
        <div className="absolute bottom-0 left-0 transform -translate-x-8 translate-y-8">
          <div className="w-24 h-24 bg-white/10 rounded-full"></div>
        </div>
        <div className="relative z-10">
          <div className="flex items-center space-x-3 mb-4">
            <div className="p-3 bg-white/20 rounded-xl">
              <Brain className="h-8 w-8 text-white" />
            </div>
            <div>
              <h1 className="text-3xl font-bold">AI Medical Documentation</h1>
              <p className="text-white/90 text-lg">Powered by Claude Sonnet 4</p>
            </div>
          </div>
          <p className="text-white/90 max-w-2xl">
            Generate comprehensive, professional medical notes from patient visits using advanced AI. 
            Save time and improve documentation quality with intelligent assistance.
          </p>
          <div className="flex items-center mt-4 space-x-4">
            <div className="flex items-center space-x-2">
              <Sparkles className="h-5 w-5" />
              <span className="text-sm">AI-Powered Analysis</span>
            </div>
            <div className="flex items-center space-x-2">
              <CheckCircle className="h-5 w-5" />
              <span className="text-sm">HIPAA Compliant</span>
            </div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Input Form */}
        <Card className="border-0 shadow-lg">
          <CardHeader>
            <CardTitle className="flex items-center space-x-2">
              <Wand2 className="h-5 w-5 text-purple-600" />
              <span>Generate Medical Notes</span>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleGenerate} className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="appointment_id">Select Appointment</Label>
                <Select 
                  value={formData.appointment_id} 
                  onValueChange={(value) => {
                    setFormData({...formData, appointment_id: value});
                    setSelectedAppointment(value);
                  }}
                  required
                >
                  <SelectTrigger data-testid="ai-appointment-select">
                    <SelectValue placeholder="Choose an appointment" />
                  </SelectTrigger>
                  <SelectContent>
                    {appointments.map((appointment) => {
                      const { patient, user: patientUser } = getPatientInfo(appointment.patient_id);
                      return (
                        <SelectItem key={appointment.id} value={appointment.id}>
                          {patientUser?.full_name || 'Unknown'} - {appointment.reason} ({formatDate(appointment.appointment_date)})
                        </SelectItem>
                      );
                    })}
                  </SelectContent>
                </Select>
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="patient_symptoms">Patient Symptoms *</Label>
                <Textarea
                  id="patient_symptoms"
                  placeholder="Describe the patient's reported symptoms and complaints..."
                  value={formData.patient_symptoms}
                  onChange={(e) => setFormData({...formData, patient_symptoms: e.target.value})}
                  rows={3}
                  required
                  data-testid="ai-symptoms-input"
                  className="resize-none"
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="examination_findings">Examination Findings *</Label>
                <Textarea
                  id="examination_findings"
                  placeholder="Document physical examination findings, vital signs, observations..."
                  value={formData.examination_findings}
                  onChange={(e) => setFormData({...formData, examination_findings: e.target.value})}
                  rows={3}
                  required
                  data-testid="ai-findings-input"
                  className="resize-none"
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="treatment_plan">Treatment Plan *</Label>
                <Textarea
                  id="treatment_plan"
                  placeholder="Outline the recommended treatment plan, medications, follow-up..."
                  value={formData.treatment_plan}
                  onChange={(e) => setFormData({...formData, treatment_plan: e.target.value})}
                  rows={3}
                  required
                  data-testid="ai-treatment-input"
                  className="resize-none"
                />
              </div>
              
              <Button 
                type="submit" 
                disabled={generating}
                className="w-full bg-purple-600 hover:bg-purple-700 text-white font-medium py-3 rounded-lg transition-all duration-200 hover:shadow-lg"
                data-testid="generate-ai-notes-btn"
              >
                {generating ? (
                  <>
                    <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                    Generating Notes...
                  </>
                ) : (
                  <>
                    <Sparkles className="h-4 w-4 mr-2" />
                    Generate AI Notes
                  </>
                )}
              </Button>
            </form>
          </CardContent>
        </Card>

        {/* Generated Notes */}
        <Card className="border-0 shadow-lg">
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle className="flex items-center space-x-2">
                <FileText className="h-5 w-5 text-blue-600" />
                <span>Generated Medical Notes</span>
              </CardTitle>
              {generatedNotes && (
                <div className="flex space-x-2">
                  <Button 
                    size="sm" 
                    variant="outline"
                    onClick={handleCopy}
                    data-testid="copy-notes-btn"
                  >
                    <Copy className="h-4 w-4" />
                  </Button>
                  <Button 
                    size="sm" 
                    variant="outline"
                    onClick={handleDownload}
                    data-testid="download-notes-btn"
                  >
                    <Download className="h-4 w-4" />
                  </Button>
                </div>
              )}
            </div>
          </CardHeader>
          <CardContent>
            {generating ? (
              <div className="flex items-center justify-center py-12">
                <div className="text-center">
                  <RefreshCw className="h-8 w-8 text-purple-600 animate-spin mx-auto mb-4" />
                  <p className="text-gray-600">Claude is analyzing the patient information...</p>
                  <p className="text-sm text-gray-500 mt-2">This may take a few moments</p>
                </div>
              </div>
            ) : generatedNotes ? (
              <div className="space-y-4">
                <div className="p-4 bg-green-50 border border-green-200 rounded-lg">
                  <div className="flex items-center space-x-2 mb-2">
                    <CheckCircle className="h-5 w-5 text-green-600" />
                    <span className="font-medium text-green-800">Notes Generated Successfully</span>
                  </div>
                  <p className="text-sm text-green-700">
                    AI-powered medical documentation is ready for review and use.
                  </p>
                </div>
                
                <div className="bg-gray-50 rounded-lg p-4 max-h-96 overflow-y-auto">
                  <pre className="whitespace-pre-wrap text-sm text-gray-800 font-mono leading-relaxed" data-testid="generated-notes">
                    {generatedNotes}
                  </pre>
                </div>
              </div>
            ) : (
              <div className="text-center py-12">
                <Brain className="h-12 w-12 text-gray-300 mx-auto mb-4" />
                <h3 className="text-lg font-medium text-gray-900 mb-2">Ready to Generate Notes</h3>
                <p className="text-gray-500">
                  Fill in the patient information on the left and click "Generate AI Notes" to create 
                  comprehensive medical documentation.
                </p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      {/* Recent Generations */}
      {recentGenerations.length > 0 && (
        <Card className="border-0 shadow-lg">
          <CardHeader>
            <CardTitle className="flex items-center space-x-2">
              <Clock className="h-5 w-5 text-blue-600" />
              <span>Recent AI Generations</span>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4" data-testid="recent-generations">
              {recentGenerations.map((appointment) => {
                const { patient, user: patientUser } = getPatientInfo(appointment.patient_id);
                const doctor = getDoctorInfo(appointment.doctor_id);
                
                return (
                  <div key={appointment.id} className="flex items-center justify-between p-4 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors">
                    <div className="flex items-center space-x-3">
                      <div className="p-2 bg-purple-100 rounded-lg">
                        <Brain className="h-4 w-4 text-purple-600" />
                      </div>
                      <div>
                        <p className="font-medium text-gray-900">
                          {patientUser?.full_name || 'Unknown'} - {appointment.reason}
                        </p>
                        <p className="text-sm text-gray-500">
                          Dr. {doctor?.full_name || 'Unknown'} • {formatDate(appointment.appointment_date)}
                        </p>
                      </div>
                    </div>
                    <Badge className="bg-green-100 text-green-800">
                      <CheckCircle className="h-3 w-3 mr-1" />
                      Generated
                    </Badge>
                  </div>
                );
              })}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Features Info */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Card className="border-0 shadow-lg bg-gradient-to-br from-blue-50 to-blue-100">
          <CardContent className="p-6 text-center">
            <div className="p-3 bg-blue-600 rounded-full w-fit mx-auto mb-4">
              <Stethoscope className="h-6 w-6 text-white" />
            </div>
            <h3 className="font-semibold text-blue-900 mb-2">Medical Accuracy</h3>
            <p className="text-sm text-blue-700">
              AI trained on medical literature ensures accurate terminology and structure
            </p>
          </CardContent>
        </Card>

        <Card className="border-0 shadow-lg bg-gradient-to-br from-green-50 to-green-100">
          <CardContent className="p-6 text-center">
            <div className="p-3 bg-green-600 rounded-full w-fit mx-auto mb-4">
              <Clock className="h-6 w-6 text-white" />
            </div>
            <h3 className="font-semibold text-green-900 mb-2">Time Saving</h3>
            <p className="text-sm text-green-700">
              Reduce documentation time by up to 70% while maintaining quality
            </p>
          </CardContent>
        </Card>

        <Card className="border-0 shadow-lg bg-gradient-to-br from-purple-50 to-purple-100">
          <CardContent className="p-6 text-center">
            <div className="p-3 bg-purple-600 rounded-full w-fit mx-auto mb-4">
              <FileText className="h-6 w-6 text-white" />
            </div>
            <h3 className="font-semibold text-purple-900 mb-2">Structured Format</h3>
            <p className="text-sm text-purple-700">
              Follows medical documentation standards with proper sections and formatting
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default AIDocumentation;